import { PERMISSION_IDS } from '@/types/permission';

// Map features to their permission IDs
export const FEATURE_PERMISSION_MAP = {
    dashboard: {
        view: [PERMISSION_IDS.DASHBOARD_VIEW],
        edit: [PERMISSION_IDS.DASHBOARD_VIEW, PERMISSION_IDS.DASHBOARD_EDIT],
    },
    manage_institute: {
        view: [PERMISSION_IDS.MANAGE_INSTITUTE_VIEW],
        edit: [PERMISSION_IDS.MANAGE_INSTITUTE_VIEW, PERMISSION_IDS.MANAGE_INSTITUTE_EDIT],
    },
    batches: {
        view: [PERMISSION_IDS.BATCHES_VIEW],
        edit: [PERMISSION_IDS.BATCHES_VIEW, PERMISSION_IDS.BATCHES_EDIT],
    },
    sessions: {
        view: [PERMISSION_IDS.SESSIONS_VIEW],
        edit: [PERMISSION_IDS.SESSIONS_VIEW, PERMISSION_IDS.SESSIONS_EDIT],
    },
    teams: {
        view: [PERMISSION_IDS.TEAMS_VIEW],
        edit: [PERMISSION_IDS.TEAMS_VIEW, PERMISSION_IDS.TEAMS_EDIT],
    },
    manage_learners: {
        view: [PERMISSION_IDS.MANAGE_LEARNERS_VIEW],
        edit: [PERMISSION_IDS.MANAGE_LEARNERS_VIEW, PERMISSION_IDS.MANAGE_LEARNERS_EDIT],
    },
    learner_list: {
        view: [PERMISSION_IDS.LEARNER_LIST_VIEW],
        edit: [PERMISSION_IDS.LEARNER_LIST_VIEW, PERMISSION_IDS.LEARNER_LIST_EDIT],
    },
    enroll_request: {
        view: [PERMISSION_IDS.ENROLL_REQUEST_VIEW],
        edit: [PERMISSION_IDS.ENROLL_REQUEST_VIEW, PERMISSION_IDS.ENROLL_REQUEST_EDIT],
    },
    invite: {
        view: [PERMISSION_IDS.INVITE_VIEW],
        edit: [PERMISSION_IDS.INVITE_VIEW, PERMISSION_IDS.INVITE_EDIT],
    },
    learning_centre: {
        view: [PERMISSION_IDS.LEARNING_CENTRE_VIEW],
        edit: [PERMISSION_IDS.LEARNING_CENTRE_VIEW, PERMISSION_IDS.LEARNING_CENTRE_EDIT],
    },
    courses: {
        view: [PERMISSION_IDS.COURSES_VIEW],
        edit: [PERMISSION_IDS.COURSES_VIEW, PERMISSION_IDS.COURSES_EDIT],
    },
    live_session: {
        view: [PERMISSION_IDS.LIVE_SESSION_VIEW],
        edit: [PERMISSION_IDS.LIVE_SESSION_VIEW, PERMISSION_IDS.LIVE_SESSION_EDIT],
    },
    doubt_management: {
        view: [PERMISSION_IDS.DOUBT_MANAGEMENT_VIEW],
        edit: [PERMISSION_IDS.DOUBT_MANAGEMENT_VIEW, PERMISSION_IDS.DOUBT_MANAGEMENT_EDIT],
    },
    reports: {
        view: [PERMISSION_IDS.REPORTS_VIEW],
        edit: [PERMISSION_IDS.REPORTS_VIEW, PERMISSION_IDS.REPORTS_EDIT],
    },
    presentation: {
        view: [PERMISSION_IDS.PRESENTATION_VIEW],
        edit: [PERMISSION_IDS.PRESENTATION_VIEW, PERMISSION_IDS.PRESENTATION_EDIT],
    },
    homework: {
        view: [PERMISSION_IDS.HOMEWORK_VIEW],
        edit: [PERMISSION_IDS.HOMEWORK_VIEW, PERMISSION_IDS.HOMEWORK_EDIT],
    },
    assessment_centre: {
        view: [PERMISSION_IDS.ASSESSMENT_CENTRE_VIEW],
        edit: [PERMISSION_IDS.ASSESSMENT_CENTRE_VIEW, PERMISSION_IDS.ASSESSMENT_CENTRE_EDIT],
    },
    assessment_list: {
        view: [PERMISSION_IDS.ASSESSMENT_LIST_VIEW],
        edit: [PERMISSION_IDS.ASSESSMENT_LIST_VIEW, PERMISSION_IDS.ASSESSMENT_LIST_EDIT],
    },
    question_paper: {
        view: [PERMISSION_IDS.QUESTION_PAPER_VIEW],
        edit: [PERMISSION_IDS.QUESTION_PAPER_VIEW, PERMISSION_IDS.QUESTION_PAPER_EDIT],
    },
    evaluation_centre: {
        view: [PERMISSION_IDS.EVALUATION_CENTRE_VIEW],
        edit: [PERMISSION_IDS.EVALUATION_CENTRE_VIEW, PERMISSION_IDS.EVALUATION_CENTRE_EDIT],
    },
    evaluation: {
        view: [PERMISSION_IDS.EVALUATION_VIEW],
        edit: [PERMISSION_IDS.EVALUATION_VIEW, PERMISSION_IDS.EVALUATION_EDIT],
    },
    evaluation_tool: {
        view: [PERMISSION_IDS.EVALUATION_TOOL_VIEW],
        edit: [PERMISSION_IDS.EVALUATION_TOOL_VIEW, PERMISSION_IDS.EVALUATION_TOOL_EDIT],
    },
    community_centre: {
        view: [PERMISSION_IDS.COMMUNITY_CENTRE_VIEW],
        edit: [PERMISSION_IDS.COMMUNITY_CENTRE_VIEW, PERMISSION_IDS.COMMUNITY_CENTRE_EDIT],
    },
    vsmart_ai_tools: {
        view: [PERMISSION_IDS.VSMART_AI_TOOLS_VIEW],
        edit: [PERMISSION_IDS.VSMART_AI_TOOLS_VIEW, PERMISSION_IDS.VSMART_AI_TOOLS_EDIT],
    },
} as const;

// Default role permissions using permission IDs
export const DEFAULT_ROLE_PERMISSIONS = {
    ADMIN: [
        // Admin gets all permissions
        ...Object.values(PERMISSION_IDS),
    ],

    TEACHER: [
        PERMISSION_IDS.DASHBOARD_VIEW,
        PERMISSION_IDS.MANAGE_INSTITUTE_VIEW,
        PERMISSION_IDS.BATCHES_VIEW,
        PERMISSION_IDS.SESSIONS_VIEW,
        PERMISSION_IDS.TEAMS_VIEW,
        PERMISSION_IDS.MANAGE_LEARNERS_VIEW,
        PERMISSION_IDS.LEARNER_LIST_VIEW,
        PERMISSION_IDS.LEARNER_LIST_EDIT,
        PERMISSION_IDS.ENROLL_REQUEST_VIEW,
        PERMISSION_IDS.LEARNING_CENTRE_VIEW,
        PERMISSION_IDS.LEARNING_CENTRE_EDIT,
        PERMISSION_IDS.COURSES_VIEW,
        PERMISSION_IDS.LIVE_SESSION_VIEW,
        PERMISSION_IDS.LIVE_SESSION_EDIT,
        PERMISSION_IDS.DOUBT_MANAGEMENT_VIEW,
        PERMISSION_IDS.DOUBT_MANAGEMENT_EDIT,
        PERMISSION_IDS.REPORTS_VIEW,
        PERMISSION_IDS.PRESENTATION_VIEW,
        PERMISSION_IDS.PRESENTATION_EDIT,
        PERMISSION_IDS.HOMEWORK_VIEW,
        PERMISSION_IDS.HOMEWORK_EDIT,
        PERMISSION_IDS.ASSESSMENT_CENTRE_VIEW,
        PERMISSION_IDS.ASSESSMENT_LIST_VIEW,
        PERMISSION_IDS.QUESTION_PAPER_VIEW,
        PERMISSION_IDS.COMMUNITY_CENTRE_VIEW,
        PERMISSION_IDS.COMMUNITY_CENTRE_EDIT,
        PERMISSION_IDS.VSMART_AI_TOOLS_VIEW,
    ],

    COURSE_CREATOR: [
        PERMISSION_IDS.DASHBOARD_VIEW,
        PERMISSION_IDS.LEARNING_CENTRE_VIEW,
        PERMISSION_IDS.LEARNING_CENTRE_EDIT,
        PERMISSION_IDS.COURSES_VIEW,
        PERMISSION_IDS.COURSES_EDIT,
        PERMISSION_IDS.PRESENTATION_VIEW,
        PERMISSION_IDS.PRESENTATION_EDIT,
        PERMISSION_IDS.REPORTS_VIEW,
        PERMISSION_IDS.COMMUNITY_CENTRE_VIEW,
        PERMISSION_IDS.COMMUNITY_CENTRE_EDIT,
        PERMISSION_IDS.VSMART_AI_TOOLS_VIEW,
    ],

    ASSESSMENT_CREATOR: [
        PERMISSION_IDS.DASHBOARD_VIEW,
        PERMISSION_IDS.ASSESSMENT_CENTRE_VIEW,
        PERMISSION_IDS.ASSESSMENT_CENTRE_EDIT,
        PERMISSION_IDS.ASSESSMENT_LIST_VIEW,
        PERMISSION_IDS.ASSESSMENT_LIST_EDIT,
        PERMISSION_IDS.QUESTION_PAPER_VIEW,
        PERMISSION_IDS.QUESTION_PAPER_EDIT,
        PERMISSION_IDS.REPORTS_VIEW,
        PERMISSION_IDS.COMMUNITY_CENTRE_VIEW,
        PERMISSION_IDS.COMMUNITY_CENTRE_EDIT,
        PERMISSION_IDS.VSMART_AI_TOOLS_VIEW,
    ],

    EVALUATOR: [
        PERMISSION_IDS.DASHBOARD_VIEW,
        PERMISSION_IDS.ASSESSMENT_CENTRE_VIEW,
        PERMISSION_IDS.ASSESSMENT_LIST_VIEW,
        PERMISSION_IDS.EVALUATION_CENTRE_VIEW,
        PERMISSION_IDS.EVALUATION_CENTRE_EDIT,
        PERMISSION_IDS.EVALUATION_VIEW,
        PERMISSION_IDS.EVALUATION_EDIT,
        PERMISSION_IDS.EVALUATION_TOOL_VIEW,
        PERMISSION_IDS.EVALUATION_TOOL_EDIT,
        PERMISSION_IDS.REPORTS_VIEW,
        PERMISSION_IDS.COMMUNITY_CENTRE_VIEW,
    ],
} as const;
