/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LoginIndexImport } from "./routes/login/index";
import { Route as DashboardIndexImport } from "./routes/dashboard/index";
import { Route as DashboardDashboardLayoutImport } from "./routes/dashboard/_dashboard-layout";
import { Route as LoginForgotPasswordIndexImport } from "./routes/login/forgot-password/index";
import { Route as DashboardDashboardLayoutHomepageIndexImport } from "./routes/dashboard/_dashboard-layout/homepage/index";

// Create Virtual Routes

const DashboardImport = createFileRoute("/dashboard")();

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
    path: "/dashboard",
    getParentRoute: () => rootRoute,
} as any);

const LoginIndexRoute = LoginIndexImport.update({
    path: "/login/",
    getParentRoute: () => rootRoute,
} as any);

const DashboardIndexRoute = DashboardIndexImport.update({
    path: "/",
    getParentRoute: () => DashboardRoute,
} as any);

const DashboardDashboardLayoutRoute = DashboardDashboardLayoutImport.update({
    id: "/_dashboard-layout",
    getParentRoute: () => DashboardRoute,
} as any);

const LoginForgotPasswordIndexRoute = LoginForgotPasswordIndexImport.update({
    path: "/login/forgot-password/",
    getParentRoute: () => rootRoute,
} as any);

const DashboardDashboardLayoutHomepageIndexRoute =
    DashboardDashboardLayoutHomepageIndexImport.update({
        path: "/homepage/",
        getParentRoute: () => DashboardDashboardLayoutRoute,
    } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/dashboard": {
            id: "/dashboard";
            path: "/dashboard";
            fullPath: "/dashboard";
            preLoaderRoute: typeof DashboardImport;
            parentRoute: typeof rootRoute;
        };
        "/dashboard/_dashboard-layout": {
            id: "/dashboard/_dashboard-layout";
            path: "/dashboard";
            fullPath: "/dashboard";
            preLoaderRoute: typeof DashboardDashboardLayoutImport;
            parentRoute: typeof DashboardRoute;
        };
        "/dashboard/": {
            id: "/dashboard/";
            path: "/";
            fullPath: "/dashboard/";
            preLoaderRoute: typeof DashboardIndexImport;
            parentRoute: typeof DashboardImport;
        };
        "/login/": {
            id: "/login/";
            path: "/login";
            fullPath: "/login";
            preLoaderRoute: typeof LoginIndexImport;
            parentRoute: typeof rootRoute;
        };
        "/login/forgot-password/": {
            id: "/login/forgot-password/";
            path: "/login/forgot-password";
            fullPath: "/login/forgot-password";
            preLoaderRoute: typeof LoginForgotPasswordIndexImport;
            parentRoute: typeof rootRoute;
        };
        "/dashboard/_dashboard-layout/homepage/": {
            id: "/dashboard/_dashboard-layout/homepage/";
            path: "/homepage";
            fullPath: "/dashboard/homepage";
            preLoaderRoute: typeof DashboardDashboardLayoutHomepageIndexImport;
            parentRoute: typeof DashboardDashboardLayoutImport;
        };
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
    DashboardRoute: DashboardRoute.addChildren({
        DashboardDashboardLayoutRoute: DashboardDashboardLayoutRoute.addChildren({
            DashboardDashboardLayoutHomepageIndexRoute,
        }),
        DashboardIndexRoute,
    }),
    LoginIndexRoute,
    LoginForgotPasswordIndexRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard",
        "/login/",
        "/login/forgot-password/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_dashboard-layout",
        "/dashboard/"
      ]
    },
    "/dashboard/_dashboard-layout": {
      "filePath": "dashboard/_dashboard-layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_dashboard-layout/homepage/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/login/forgot-password/": {
      "filePath": "login/forgot-password/index.tsx"
    },
    "/dashboard/_dashboard-layout/homepage/": {
      "filePath": "dashboard/_dashboard-layout/homepage/index.tsx",
      "parent": "/dashboard/_dashboard-layout"
    }
  }
}
ROUTE_MANIFEST_END */
